/// C code generator backend.
///
/// Translates an IrModule into a self-contained C file that can be compiled
/// with any standard C compiler (gcc, clang, tcc) on any platform.
use rym_ir::{BasicBlock, IrFunc, IrModule, IrTy, Op, Terminator};
use std::collections::HashMap;
use std::fmt::Write;

pub struct CCodegen {
    out: String,
    /// Indentation level inside a function body.
    indent: usize,
    /// Set of function names that return void.
    void_fns: std::collections::HashSet<String>,
    /// Struct field layouts: type name → (field name → index).
    struct_layouts: HashMap<String, HashMap<String, usize>>,
}

impl CCodegen {
    pub fn new() -> Self {
        let mut void_fns = std::collections::HashSet::new();
        // Built-in void functions.
        void_fns.insert("println".into());
        void_fns.insert("print".into());
        void_fns.insert("__rym_println".into());
        void_fns.insert("__rym_main".into());
        Self { out: String::new(), indent: 0, void_fns, struct_layouts: HashMap::new() }
    }

    pub fn emit_module(&mut self, module: &IrModule) -> String {
        self.out.clear();

        // Standard prelude.
        self.line("/* Generated by rymc — do not edit */");
        self.line("#include <stdint.h>");
        self.line("#include <stddef.h>");
        self.line("#include <stdio.h>");
        self.line("#include <stdlib.h>");
        self.line("#include <string.h>");
        self.line("");

        // Rym built-in type aliases.
        self.line("typedef int8_t   i8;");
        self.line("typedef int16_t  i16;");
        self.line("typedef int32_t  i32;");
        self.line("typedef int64_t  i64;");
        self.line("typedef uint8_t  u8;");
        self.line("typedef uint16_t u16;");
        self.line("typedef uint32_t u32;");
        self.line("typedef uint64_t u64;");
        self.line("typedef float    f32;");
        self.line("typedef double   f64;");
        self.line("typedef size_t   usize;");
        self.line("typedef char*    str;");
        self.line("typedef int      bool_t;");
        self.line("#define true  1");
        self.line("#define false 0");
        self.line("");

        // Rym Result type (simple tagged union).
        // String concat helper.
        self.line("static uintptr_t __str_concat(uintptr_t a, uintptr_t b) {");
        self.line("    str sa = (str)a; str sb = (str)b;");
        self.line("    size_t la = strlen(sa), lb = strlen(sb);");
        self.line("    str r = (str)malloc(la + lb + 1);");
        self.line("    memcpy(r, sa, la); memcpy(r + la, sb, lb); r[la+lb] = 0;");
        self.line("    return (uintptr_t)r;");
        self.line("}");
        self.line("");

        self.line("typedef struct { int is_ok; union { void* ok; void* err; } val; } RymResult;");
        self.line("#define Ok(v)  ((RymResult){ .is_ok=1, .val.ok=(void*)(uintptr_t)(v) })");
        self.line("#define Err(v) ((RymResult){ .is_ok=0, .val.err=(void*)(uintptr_t)(v) })");
        self.line("");

        // Build struct field-index lookup tables.
        for s in &module.structs {
            let map: HashMap<String, usize> = s.fields.iter()
                .enumerate()
                .map(|(i, n)| (n.clone(), i))
                .collect();
            self.struct_layouts.insert(s.name.clone(), map);
        }

        // Register which user functions return void.
        for func in &module.funcs {
            if func.ret == IrTy::Void {
                self.void_fns.insert(func.name.clone());
            }
        }

        // Forward-declare all functions so order doesn't matter.
        for func in &module.funcs {
            if func.name == "__main" { continue; }
            let sig = self.fn_signature(func);
            writeln!(self.out, "{sig};").unwrap();
        }
        self.line("");

        // Emit each function.
        for func in &module.funcs {
            self.emit_func(func);
        }

        // Entry point: call __main from C main.
        self.line("int main(int argc, char** argv) {");
        self.line("    __rym_main();");
        self.line("    return 0;");
        self.line("}");
        self.line("");

        self.out.clone()
    }

    fn emit_func(&mut self, func: &IrFunc) {
        let sig = self.fn_signature(func);
        // __main → __rym_main to avoid clashing with C main.
        let sig = sig.replace("void __main(", "void __rym_main(");
        writeln!(self.out, "{sig} {{").unwrap();
        self.indent = 1;

        // Declare all SSA temps as local variables.
        let max_ssa = count_ssa(func);
        for i in 0..max_ssa {
            self.iline(&format!("uintptr_t _s{i} = 0;"));
        }
        // Declare named variables (Store destinations that are not SSA names).
        let named = collect_named_vars(func);
        for n in &named {
            self.iline(&format!("uintptr_t {n} = 0;"));
        }
        if max_ssa > 0 || !named.is_empty() { self.line(""); }

        for block in &func.blocks {
            self.emit_block(block, func);
        }

        self.indent = 0;
        self.line("}");
        self.line("");
    }

    fn emit_block(&mut self, block: &BasicBlock, func: &IrFunc) {
        // Label — only emit if it could be jumped to.
        writeln!(self.out, "  lbl_{}_{}:;", func.name.replace("__", "_"), block.label).unwrap();

        for instr in &block.instrs {
            self.emit_instr(instr);
        }
        self.emit_term(&block.term, func);
    }

    fn emit_instr(&mut self, instr: &rym_ir::Instr) {
        let dest = instr.dest.as_deref().map(ssa_var);

        match &instr.op {
            Op::ConstInt(v) => {
                if let Some(d) = dest {
                    self.iline(&format!("{d} = (uintptr_t){v}LL;"));
                }
            }
            Op::ConstFloat(v) => {
                if let Some(d) = dest {
                    // Store float bits as integer for now.
                    self.iline(&format!("{d} = (uintptr_t){v};"));
                }
            }
            Op::ConstBool(v) => {
                if let Some(d) = dest {
                    self.iline(&format!("{d} = {};", if *v { 1 } else { 0 }));
                }
            }
            Op::ConstStr(s) => {
                if let Some(d) = dest {
                    let escaped = escape_c_str(s);
                    self.iline(&format!("{d} = (uintptr_t)\"{escaped}\";"));
                }
            }

            Op::Load(src) => {
                if let Some(d) = dest {
                    let s = ssa_or_var(src);
                    self.iline(&format!("{d} = (uintptr_t){s};"));
                }
            }
            Op::Store { dest: slot, src } => {
                let s = ssa_or_var(src);
                let sl = ssa_or_var(slot);
                self.iline(&format!("{sl} = (uintptr_t){s};"));
            }

            Op::Add(a, b) => arith!(self, dest, a, b, "+"),
            Op::Sub(a, b) => arith!(self, dest, a, b, "-"),
            Op::Mul(a, b) => arith!(self, dest, a, b, "*"),
            Op::Div(a, b) => arith!(self, dest, a, b, "/"),
            Op::Rem(a, b) => arith!(self, dest, a, b, "%"),

            Op::CmpEq(a, b)  => cmp!(self, dest, a, b, "=="),
            Op::CmpNeq(a, b) => cmp!(self, dest, a, b, "!="),
            Op::CmpLt(a, b)  => cmp!(self, dest, a, b, "<"),
            Op::CmpLe(a, b)  => cmp!(self, dest, a, b, "<="),
            Op::CmpGt(a, b)  => cmp!(self, dest, a, b, ">"),
            Op::CmpGe(a, b)  => cmp!(self, dest, a, b, ">="),

            Op::And(a, b) => cmp!(self, dest, a, b, "&&"),
            Op::Or(a, b)  => cmp!(self, dest, a, b, "||"),
            Op::Not(a) => {
                if let Some(d) = dest {
                    let s = ssa_or_var(a);
                    self.iline(&format!("{d} = !{s};"));
                }
            }
            Op::Neg(a) => {
                if let Some(d) = dest {
                    let s = ssa_or_var(a);
                    self.iline(&format!("{d} = (uintptr_t)(-(intptr_t){s});"));
                }
            }

            Op::Call { func: fname, args } => {
                let arg_str = args.iter().map(|a| ssa_or_var(a)).collect::<Vec<_>>().join(", ");
                let c_func = match fname.as_str() {
                    "print"   => "printf",
                    "println" => "__rym_println",
                    "__main"  => "__rym_main",
                    other     => other,
                };
                let is_void = self.void_fns.contains(c_func)
                    || matches!(c_func, "printf");
                if let Some(d) = dest {
                    if is_void {
                        self.iline(&format!("{c_func}({arg_str});"));
                        self.iline(&format!("{d} = 0;"));
                    } else {
                        self.iline(&format!("{d} = (uintptr_t){c_func}({arg_str});"));
                    }
                } else {
                    self.iline(&format!("{c_func}({arg_str});"));
                }
            }

            Op::WrapOk(v) => {
                if let Some(d) = dest {
                    let s = ssa_or_var(v);
                    self.iline(&format!("{d} = (uintptr_t)({s});  /* Ok */"));
                }
            }
            Op::WrapErr(v) => {
                if let Some(d) = dest {
                    let s = ssa_or_var(v);
                    self.iline(&format!("{d} = (uintptr_t)({s});  /* Err */"));
                }
            }
            Op::UnwrapOk { val, err_block } => {
                if let Some(d) = dest {
                    let s = ssa_or_var(val);
                    self.iline(&format!("{d} = {s};  /* unwrap or goto {err_block} */"));
                }
            }

            Op::Cast { val, ty } => {
                if let Some(d) = dest {
                    let s  = ssa_or_var(val);
                    let ct = ir_ty_to_c(ty);
                    self.iline(&format!("{d} = (uintptr_t)({ct}){s};"));
                }
            }

            Op::Field { base, field, struct_ty } => {
                if let Some(d) = dest {
                    let b = ssa_or_var(base);
                    // Look up field index from struct layout table.
                    let idx = struct_ty.as_deref()
                        .and_then(|ty| self.struct_layouts.get(ty))
                        .and_then(|m| m.get(field))
                        .copied()
                        .unwrap_or(0);
                    self.iline(&format!("{d} = ((uintptr_t*){b})[{idx}];  /* .{field} */"));
                }
            }

            Op::Index { base, index } => {
                if let Some(d) = dest {
                    let b = ssa_or_var(base);
                    let i = ssa_or_var(index);
                    self.iline(&format!("{d} = ((uintptr_t*){b})[{i}];"));
                }
            }

            Op::Ref(v) => {
                if let Some(d) = dest {
                    let s = ssa_or_var(v);
                    self.iline(&format!("{d} = (uintptr_t)(&{s});"));
                }
            }
            Op::Deref(v) => {
                if let Some(d) = dest {
                    let s = ssa_or_var(v);
                    self.iline(&format!("{d} = *(uintptr_t*){s};"));
                }
            }

            Op::ArrayLit(elems) => {
                if let Some(d) = dest {
                    let n = elems.len();
                    self.iline(&format!("{d} = (uintptr_t)malloc({n} * sizeof(uintptr_t));"));
                    for (i, ev) in elems.iter().enumerate() {
                        let v = ssa_or_var(ev);
                        self.iline(&format!("((uintptr_t*){d})[{i}] = (uintptr_t){v};"));
                    }
                }
            }

            Op::MatrixLit { elems, rows, cols } => {
                if let Some(d) = dest {
                    let n = elems.len();
                    self.iline(&format!("{d} = (uintptr_t)malloc({n} * sizeof(uintptr_t));  /* matrix {rows}x{cols} */"));
                    for (i, ev) in elems.iter().enumerate() {
                        let v = ssa_or_var(ev);
                        self.iline(&format!("((uintptr_t*){d})[{i}] = (uintptr_t){v};"));
                    }
                }
            }

            Op::AllocCall { allocator, elem_ty, count } => {
                if let Some(d) = dest {
                    let _ = allocator;
                    let ct = ir_ty_to_c(elem_ty);
                    let cnt = ssa_or_var(count);
                    self.iline(&format!("{d} = (uintptr_t)malloc((usize)({cnt}) * sizeof({ct}));"));
                }
            }

            Op::StructLit { ty, fields } => {
                if let Some(d) = dest {
                    // Allocate on the C heap and fill fields.
                    let n = fields.len();
                    self.iline(&format!("{d} = (uintptr_t)malloc({n} * sizeof(uintptr_t));  /* {ty} */"));
                    for (i, (fname, fval)) in fields.iter().enumerate() {
                        let fv = ssa_or_var(fval);
                        self.iline(&format!("((uintptr_t*){d})[{i}] = (uintptr_t){fv};  /* .{fname} */"));
                    }
                }
            }

            Op::Nop => {
                self.iline("/* nop */");
            }
        }
    }

    fn emit_term(&mut self, term: &Terminator, func: &IrFunc) {
        let lbl = |l: &str| format!("lbl_{}_{}", func.name.replace("__", "_"), l);
        let is_void = func.ret == IrTy::Void;
        match term {
            Terminator::Return(val) => {
                if let Some(v) = val {
                    let s = ssa_or_var(v);
                    self.iline(&format!("return (uintptr_t){s};"));
                } else if is_void {
                    self.iline("return;");
                } else {
                    self.iline("return 0;");
                }
            }
            Terminator::Jump(l) => {
                self.iline(&format!("goto {};", lbl(l)));
            }
            Terminator::Branch { cond, then_block, else_block } => {
                let c = ssa_or_var(cond);
                self.iline(&format!("if ({c}) goto {}; else goto {};", lbl(then_block), lbl(else_block)));
            }
            Terminator::Unreachable => {
                self.iline("__builtin_unreachable();");
            }
        }
    }

    // ── Helpers ───────────────────────────────────────────────

    fn fn_signature(&self, func: &IrFunc) -> String {
        let ret: &str = if func.ret == IrTy::Void { "void" } else { "uintptr_t" };
        let params = if func.params.is_empty() {
            "void".into()
        } else {
            func.params.iter()
                .map(|p| format!("uintptr_t {}", c_safe_name(&p.name)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        format!("{ret} {name}({params})", name = func.name)
    }

    fn line(&mut self, s: &str) {
        writeln!(self.out, "{s}").unwrap();
    }

    fn iline(&mut self, s: &str) {
        let pad = "    ".repeat(self.indent);
        writeln!(self.out, "{pad}{s}").unwrap();
    }
}

impl Default for CCodegen {
    fn default() -> Self { Self::new() }
}

// ── Utility helpers ───────────────────────────────────────────

/// Turn an SSA name like `%3` into a C variable name `_s3`.
fn ssa_var(name: &str) -> String {
    if let Some(n) = name.strip_prefix('%') {
        format!("_s{n}")
    } else {
        c_safe_name(name)
    }
}

/// Get the C expression for an SSA name or a named variable.
fn ssa_or_var(name: &str) -> String {
    if let Some(n) = name.strip_prefix('%') {
        format!("_s{n}")
    } else {
        c_safe_name(name)
    }
}

/// Replace chars that are not valid in C identifiers.
fn c_safe_name(name: &str) -> String {
    name.chars().map(|c| {
        if c.is_alphanumeric() || c == '_' { c } else { '_' }
    }).collect()
}

fn ir_ty_to_c(ty: &IrTy) -> &'static str {
    match ty {
        IrTy::I8    => "i8",
        IrTy::I16   => "i16",
        IrTy::I32   => "i32",
        IrTy::I64   => "i64",
        IrTy::U8    => "u8",
        IrTy::U16   => "u16",
        IrTy::U32   => "u32",
        IrTy::U64   => "u64",
        IrTy::F32   => "f32",
        IrTy::F64   => "f64",
        IrTy::Usize => "usize",
        IrTy::Bool  => "bool_t",
        IrTy::Str   => "str",
        _           => "uintptr_t",
    }
}

fn escape_c_str(s: &str) -> String {
    s.chars().flat_map(|c| match c {
        '"'  => vec!['\\', '"'],
        '\\' => vec!['\\', '\\'],
        '\n' => vec!['\\', 'n'],
        '\t' => vec!['\\', 't'],
        '\r' => vec!['\\', 'r'],
        c    => vec![c],
    }).collect()
}

/// Collect all named (non-SSA) variable destinations so we can declare them.
fn collect_named_vars(func: &IrFunc) -> Vec<String> {
    let mut vars = std::collections::BTreeSet::new();
    for block in &func.blocks {
        for instr in &block.instrs {
            // Named dest (e.g. `msg = Load(%0)`)
            if let Some(dest) = &instr.dest {
                if !dest.starts_with('%') {
                    vars.insert(c_safe_name(dest));
                }
            }
            // Store op dest
            if let Op::Store { dest, .. } = &instr.op {
                if !dest.starts_with('%') {
                    vars.insert(c_safe_name(dest));
                }
            }
        }
    }
    vars.into_iter().collect()
}

fn count_ssa(func: &IrFunc) -> usize {
    let mut max = 0usize;
    for block in &func.blocks {
        for instr in &block.instrs {
            if let Some(d) = &instr.dest {
                if let Some(n) = d.strip_prefix('%') {
                    if let Ok(v) = n.parse::<usize>() {
                        max = max.max(v + 1);
                    }
                }
            }
        }
    }
    max
}

// ── Helper macros ─────────────────────────────────────────────

macro_rules! arith {
    ($self:expr, $dest:expr, $a:expr, $b:expr, $op:literal) => {
        if let Some(d) = $dest {
            let a = ssa_or_var($a);
            let b = ssa_or_var($b);
            $self.iline(&format!("{d} = (uintptr_t)((intptr_t){a} {} (intptr_t){b});", $op));
        }
    };
}

macro_rules! cmp {
    ($self:expr, $dest:expr, $a:expr, $b:expr, $op:literal) => {
        if let Some(d) = $dest {
            let a = ssa_or_var($a);
            let b = ssa_or_var($b);
            $self.iline(&format!("{d} = (uintptr_t)((intptr_t){a} {} (intptr_t){b});", $op));
        }
    };
}

use arith;
use cmp;

// ── Helper: emit a println wrapper ───────────────────────────

/// Returns a small C helper that rymc inserts at the top when `println` is used.
pub fn println_helper() -> &'static str {
    "#include <stdio.h>\nstatic void __rym_println(uintptr_t s) { puts((const char*)s); }\n"
}
